// Generated by JFlex 1.9.1 http://jflex.de/  (tweaked for IntelliJ platform)
// source: itrules.flex

package io.intino.plugin.itrules.lang.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import io.intino.plugin.itrules.lang.psi.ItrulesTypes;


class ItrulesLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\10\u2f00\31\u1f00\1\u0100\1\u3000\1\u3100\1\u0100\1\u3200"+
    "\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u3a00"+
    "\1\u0100\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100"+
    "\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800\1\u4900"+
    "\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u1f00\1\u4f00\1\u5000"+
    "\1\u5100\1\u5200\3\u0100\1\u5300\1\u5400\1\u5500\12\u1f00\4\u0100"+
    "\1\u5600\17\u1f00\2\u0100\1\u5700\41\u1f00\2\u0100\1\u5800\1\u5900"+
    "\2\u1f00\1\u5a00\1\u5b00\27\u0100\1\u5c00\4\u0100\1\u5d00\1\u5e00"+
    "\42\u1f00\1\u0100\1\u5f00\1\u6000\11\u1f00\1\u6100\24\u1f00\1\u6200"+
    "\1\u6300\1\u1f00\1\u6400\1\u6500\1\u6600\1\u6700\2\u1f00\1\u6800"+
    "\5\u1f00\1\u6900\1\u6a00\1\u6b00\5\u1f00\1\u6c00\1\u6d00\2\u1f00"+
    "\1\u6e00\1\u1f00\1\u6f00\14\u1f00\1\u7000\4\u1f00\246\u0100\1\u7100"+
    "\20\u0100\1\u7200\1\u7300\25\u0100\1\u7400\34\u0100\1\u7500\14\u1f00"+
    "\2\u0100\1\u7600\5\u1f00\23\u0100\1\u7700\u0aec\u1f00\1\u7800\1\u7900"+
    "\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\5\1\16\0\10\1\1\2\6\1\1\3\1\1"+
    "\1\0\2\1\12\0\7\1\32\4\1\5\1\1\1\6"+
    "\1\1\1\4\1\1\3\4\1\7\1\10\1\11\7\4"+
    "\1\12\14\4\4\1\41\0\2\1\4\4\4\1\1\4"+
    "\2\1\1\0\7\1\1\4\4\1\1\4\5\1\27\4"+
    "\1\1\37\4\1\1\u01ca\4\4\1\14\4\16\1\5\4"+
    "\7\1\1\4\1\1\1\4\21\1\160\0\5\4\1\1"+
    "\2\4\2\1\4\4\1\1\1\4\6\1\1\4\1\1"+
    "\3\4\1\1\1\4\1\1\24\4\1\1\123\4\1\1"+
    "\213\4\1\1\5\0\2\1\246\4\1\1\46\4\2\1"+
    "\1\4\6\1\51\4\6\1\1\4\1\1\55\0\1\1"+
    "\1\0\1\1\2\0\1\1\2\0\1\1\1\0\10\1"+
    "\33\4\4\1\4\4\15\1\6\0\5\1\1\4\4\1"+
    "\13\0\1\1\1\0\3\1\53\4\37\0\4\1\2\4"+
    "\1\0\143\4\1\1\1\4\10\0\1\1\6\0\2\4"+
    "\2\0\1\1\4\0\2\4\12\0\3\4\2\1\1\4"+
    "\17\1\1\0\1\4\1\0\36\4\33\0\2\1\131\4"+
    "\13\0\1\4\16\1\12\0\41\4\11\0\2\4\4\1"+
    "\1\4\2\1\1\0\30\4\4\0\1\4\11\0\1\4"+
    "\3\0\1\4\5\0\22\1\31\4\3\0\4\1\13\4"+
    "\65\1\25\4\1\1\22\4\13\1\61\0\66\4\3\0"+
    "\1\4\22\0\1\4\7\0\12\4\2\0\2\1\12\0"+
    "\1\1\20\4\3\0\1\1\10\4\2\1\2\4\2\1"+
    "\26\4\1\1\7\4\1\1\1\4\3\1\4\4\2\1"+
    "\1\0\1\4\7\0\2\1\2\0\2\1\3\0\1\4"+
    "\10\1\1\0\4\1\2\4\1\1\3\4\2\0\2\1"+
    "\12\0\4\4\7\1\2\4\1\1\1\0\2\1\3\0"+
    "\1\1\6\4\4\1\2\4\2\1\26\4\1\1\7\4"+
    "\1\1\2\4\1\1\2\4\1\1\2\4\2\1\1\0"+
    "\1\1\5\0\4\1\2\0\2\1\3\0\3\1\1\0"+
    "\7\1\4\4\1\1\1\4\7\1\14\0\3\4\1\0"+
    "\13\1\3\0\1\1\11\4\1\1\3\4\1\1\26\4"+
    "\1\1\7\4\1\1\2\4\1\1\5\4\2\1\1\0"+
    "\1\4\10\0\1\1\3\0\1\1\3\0\2\1\1\4"+
    "\17\1\2\4\2\0\2\1\12\0\1\1\1\4\7\1"+
    "\1\4\6\0\1\1\3\0\1\1\10\4\2\1\2\4"+
    "\2\1\26\4\1\1\7\4\1\1\2\4\1\1\5\4"+
    "\2\1\1\0\1\4\7\0\2\1\2\0\2\1\3\0"+
    "\7\1\3\0\4\1\2\4\1\1\3\4\2\0\2\1"+
    "\12\0\1\1\1\4\20\1\1\0\1\4\1\1\6\4"+
    "\3\1\3\4\1\1\4\4\3\1\2\4\1\1\1\4"+
    "\1\1\2\4\3\1\2\4\3\1\3\4\3\1\14\4"+
    "\4\1\5\0\3\1\3\0\1\1\4\0\2\1\1\4"+
    "\6\1\1\0\16\1\12\0\11\1\1\4\6\1\5\0"+
    "\10\4\1\1\3\4\1\1\27\4\1\1\20\4\3\1"+
    "\1\4\7\0\1\1\3\0\1\1\4\0\7\1\2\0"+
    "\1\1\3\4\5\1\2\4\2\0\2\1\12\0\20\1"+
    "\1\4\3\0\1\1\10\4\1\1\3\4\1\1\27\4"+
    "\1\1\12\4\1\1\5\4\2\1\1\0\1\4\7\0"+
    "\1\1\3\0\1\1\4\0\7\1\2\0\7\1\1\4"+
    "\1\1\2\4\2\0\2\1\12\0\1\1\2\4\15\1"+
    "\4\0\11\4\1\1\3\4\1\1\51\4\2\0\1\4"+
    "\7\0\1\1\3\0\1\1\4\0\1\4\5\1\3\4"+
    "\1\0\7\1\3\4\2\0\2\1\12\0\12\1\6\4"+
    "\1\1\3\0\1\1\22\4\3\1\30\4\1\1\11\4"+
    "\1\1\1\4\2\1\7\4\3\1\1\0\4\1\6\0"+
    "\1\1\1\0\1\1\10\0\6\1\12\0\2\1\2\0"+
    "\15\1\60\4\1\0\2\4\7\0\4\1\10\4\10\0"+
    "\1\1\12\0\47\1\2\4\1\1\1\4\1\1\5\4"+
    "\1\1\30\4\1\1\1\4\1\1\12\4\1\0\2\4"+
    "\11\0\1\4\2\1\5\4\1\1\1\4\1\1\6\0"+
    "\2\1\12\0\2\1\4\4\40\1\1\4\27\1\2\0"+
    "\6\1\12\0\13\1\1\0\1\1\1\0\1\1\1\0"+
    "\4\1\2\0\10\4\1\1\44\4\4\1\24\0\1\1"+
    "\2\0\5\4\13\0\1\1\44\0\11\1\1\0\71\1"+
    "\53\4\24\0\1\4\12\0\6\1\6\4\4\0\4\4"+
    "\3\0\1\4\3\0\2\4\7\0\3\4\4\0\15\4"+
    "\14\0\1\4\17\0\2\1\46\4\1\1\1\4\5\1"+
    "\1\4\2\1\53\4\1\1\115\4\1\1\4\4\2\1"+
    "\7\4\1\1\1\4\1\1\4\4\2\1\51\4\1\1"+
    "\4\4\2\1\41\4\1\1\4\4\2\1\7\4\1\1"+
    "\1\4\1\1\4\4\2\1\17\4\1\1\71\4\1\1"+
    "\4\4\2\1\103\4\2\1\3\0\40\1\20\4\20\1"+
    "\126\4\2\1\6\4\3\1\u016c\4\2\1\21\4\1\1"+
    "\32\4\5\1\113\4\3\1\13\4\7\1\15\4\1\1"+
    "\4\4\3\0\13\1\22\4\3\0\13\1\22\4\2\0"+
    "\14\1\15\4\1\1\3\4\1\1\2\0\14\1\64\4"+
    "\40\0\3\1\1\4\3\1\2\4\1\0\2\1\12\0"+
    "\41\1\4\0\1\1\12\0\6\1\131\4\7\1\5\4"+
    "\2\0\42\4\1\0\1\4\5\1\106\4\12\1\37\4"+
    "\1\1\14\0\4\1\14\0\12\1\12\0\36\4\2\1"+
    "\5\4\13\1\54\4\4\1\32\4\6\1\12\0\46\1"+
    "\27\4\5\0\4\1\65\4\12\0\1\1\35\0\2\1"+
    "\13\0\6\1\12\0\15\1\1\4\10\1\16\0\1\1"+
    "\2\0\77\1\5\0\57\4\21\0\7\4\4\1\12\0"+
    "\21\1\11\0\14\1\3\0\36\4\15\0\2\4\12\0"+
    "\54\4\16\0\14\1\44\4\24\0\10\1\12\0\3\1"+
    "\3\4\12\0\44\4\2\1\11\4\7\1\53\4\2\1"+
    "\3\4\20\1\3\0\1\1\25\0\4\4\1\0\6\4"+
    "\1\0\2\4\3\0\1\4\5\1\300\4\72\0\1\1"+
    "\5\0\26\4\2\1\6\4\2\1\46\4\2\1\6\4"+
    "\2\1\10\4\1\1\1\4\1\1\1\4\1\1\1\4"+
    "\1\1\37\4\2\1\65\4\1\1\7\4\1\1\1\4"+
    "\3\1\3\4\1\1\7\4\3\1\4\4\2\1\6\4"+
    "\4\1\15\4\5\1\3\4\1\1\7\4\16\1\5\0"+
    "\32\1\5\0\20\1\2\4\23\1\1\4\13\1\5\0"+
    "\1\1\12\0\1\1\1\4\15\1\1\4\20\1\15\4"+
    "\3\1\40\4\20\1\15\0\4\1\1\0\3\1\14\0"+
    "\21\1\1\4\4\1\1\4\2\1\12\4\1\1\1\4"+
    "\3\1\5\4\6\1\1\4\1\1\1\4\1\1\1\4"+
    "\1\1\4\4\1\1\13\4\2\1\4\4\5\1\5\4"+
    "\4\1\1\4\21\1\51\4\u0177\1\57\4\1\1\57\4"+
    "\1\1\205\4\6\1\4\4\3\0\2\4\14\1\46\4"+
    "\1\1\1\4\5\1\1\4\2\1\70\4\7\1\1\4"+
    "\17\1\1\0\27\4\11\1\7\4\1\1\7\4\1\1"+
    "\7\4\1\1\7\4\1\1\7\4\1\1\7\4\1\1"+
    "\7\4\1\1\7\4\1\1\40\0\57\1\1\4\325\1"+
    "\3\4\31\1\11\4\6\0\1\1\5\4\2\1\5\4"+
    "\4\1\126\4\2\1\2\0\2\1\3\4\1\1\132\4"+
    "\1\1\4\4\5\1\53\4\1\1\136\4\21\1\40\4"+
    "\60\1\320\4\100\1\375\4\3\1\215\4\103\1\56\4"+
    "\2\1\15\4\3\1\20\4\12\0\2\4\24\1\57\4"+
    "\1\0\4\1\12\0\1\1\37\4\2\0\120\4\2\0"+
    "\45\1\11\4\2\1\147\4\2\1\65\4\2\1\11\4"+
    "\52\1\15\4\1\0\3\4\1\0\4\4\1\0\27\4"+
    "\5\0\4\1\1\0\13\1\1\4\7\1\64\4\14\1"+
    "\2\0\62\4\22\0\12\1\12\0\6\1\22\0\6\4"+
    "\3\1\1\4\1\1\2\4\13\0\34\4\10\0\2\1"+
    "\27\4\15\0\14\1\35\4\3\1\4\0\57\4\16\0"+
    "\16\1\1\4\12\0\6\1\5\4\1\0\12\4\12\0"+
    "\5\4\1\1\51\4\16\0\11\1\3\4\1\0\10\4"+
    "\2\0\2\1\12\0\6\1\27\4\3\1\1\4\3\0"+
    "\62\4\1\0\1\4\3\0\2\4\2\0\5\4\2\0"+
    "\1\4\1\0\1\4\30\1\3\4\2\1\13\4\5\0"+
    "\2\1\3\4\2\0\12\1\6\4\2\1\6\4\2\1"+
    "\6\4\11\1\7\4\1\1\7\4\1\1\53\4\1\1"+
    "\16\4\6\1\163\4\10\0\1\1\2\0\2\1\12\0"+
    "\6\1\244\4\14\1\27\4\4\1\61\4\u0104\1\156\4"+
    "\2\1\152\4\46\1\7\4\14\1\5\4\5\1\1\4"+
    "\1\0\12\4\1\1\15\4\1\1\5\4\1\1\1\4"+
    "\1\1\2\4\1\1\2\4\1\1\154\4\41\1\153\4"+
    "\22\1\100\4\2\1\66\4\50\1\15\4\3\1\20\0"+
    "\20\1\20\0\3\1\2\4\30\1\3\4\31\1\1\4"+
    "\6\1\5\4\1\1\207\4\2\1\1\0\4\1\1\4"+
    "\13\1\12\0\7\1\32\4\4\1\1\4\1\1\32\4"+
    "\13\1\131\4\3\1\6\4\2\1\6\4\2\1\6\4"+
    "\2\1\3\4\3\1\2\4\3\1\2\4\22\1\3\0"+
    "\4\1\14\4\1\1\32\4\1\1\23\4\1\1\2\4"+
    "\1\1\17\4\2\1\16\4\42\1\173\4\105\1\65\4"+
    "\210\1\1\0\202\1\35\4\3\1\61\4\17\1\1\0"+
    "\37\1\40\4\15\1\36\4\5\1\46\4\5\0\5\1"+
    "\36\4\2\1\44\4\4\1\10\4\1\1\5\4\52\1"+
    "\236\4\2\1\12\0\6\1\44\4\4\1\44\4\4\1"+
    "\50\4\10\1\64\4\234\1\67\4\11\1\26\4\12\1"+
    "\10\4\230\1\6\4\2\1\1\4\1\1\54\4\1\1"+
    "\2\4\3\1\1\4\2\1\27\4\12\1\27\4\11\1"+
    "\37\4\101\1\23\4\1\1\2\4\12\1\26\4\12\1"+
    "\32\4\106\1\70\4\6\1\2\4\100\1\1\4\3\0"+
    "\1\1\2\0\5\1\4\0\4\4\1\1\3\4\1\1"+
    "\35\4\2\1\3\0\4\1\1\0\40\1\35\4\3\1"+
    "\35\4\43\1\10\4\1\1\34\4\2\0\31\1\66\4"+
    "\12\1\26\4\12\1\23\4\15\1\22\4\156\1\111\4"+
    "\67\1\63\4\15\1\63\4\15\1\44\4\4\0\10\1"+
    "\12\0\u0146\1\52\4\1\1\2\0\3\1\2\4\116\1"+
    "\35\4\12\1\1\4\10\1\26\4\13\0\137\1\25\4"+
    "\33\1\27\4\11\1\3\0\65\4\17\0\37\1\12\0"+
    "\17\1\4\0\55\4\13\0\2\1\1\0\17\1\1\0"+
    "\2\1\31\4\7\1\12\0\6\1\3\0\44\4\16\0"+
    "\1\1\12\0\4\1\1\4\2\0\1\4\10\1\43\4"+
    "\1\0\2\1\1\4\11\1\3\0\60\4\16\0\4\4"+
    "\4\1\4\0\1\1\14\0\1\4\1\1\1\4\43\1"+
    "\22\4\1\1\31\4\14\0\6\1\1\0\101\1\7\4"+
    "\1\1\1\4\1\1\4\4\1\1\17\4\1\1\12\4"+
    "\7\1\57\4\14\0\5\1\12\0\6\1\4\0\1\1"+
    "\10\4\2\1\2\4\2\1\26\4\1\1\7\4\1\1"+
    "\2\4\1\1\5\4\1\1\2\0\1\4\7\0\2\1"+
    "\2\0\2\1\3\0\2\1\1\4\6\1\1\0\5\1"+
    "\5\4\2\0\2\1\7\0\3\1\5\0\213\1\65\4"+
    "\22\0\4\4\5\1\12\0\4\1\1\0\3\4\36\1"+
    "\60\4\24\0\2\4\1\1\1\4\10\1\12\0\246\1"+
    "\57\4\7\0\2\1\11\0\27\1\4\4\2\0\42\1"+
    "\60\4\21\0\3\1\1\4\13\1\12\0\46\1\53\4"+
    "\15\0\1\4\7\1\12\0\66\1\33\4\2\1\17\0"+
    "\4\1\12\0\306\1\54\4\17\0\145\1\100\4\12\0"+
    "\25\1\10\4\2\1\1\4\2\1\10\4\1\1\2\4"+
    "\1\1\30\4\6\0\1\1\2\0\2\1\4\0\1\4"+
    "\1\0\1\4\2\0\14\1\12\0\106\1\10\4\2\1"+
    "\47\4\7\0\2\1\7\0\1\4\1\1\1\4\1\0"+
    "\33\1\1\4\12\0\50\4\7\0\1\4\4\0\10\1"+
    "\1\0\10\1\1\4\13\0\56\4\20\0\3\1\1\4"+
    "\42\1\71\4\7\1\11\4\1\1\45\4\10\0\1\1"+
    "\10\0\1\4\17\1\12\0\30\1\36\4\2\1\26\0"+
    "\1\1\16\0\111\1\7\4\1\1\2\4\1\1\46\4"+
    "\6\0\3\1\1\0\1\1\2\0\1\1\7\0\1\4"+
    "\1\0\10\1\12\0\6\1\6\4\1\1\2\4\1\1"+
    "\40\4\5\0\1\1\2\0\1\1\5\0\1\4\7\1"+
    "\12\0\u0136\1\23\4\4\0\271\1\1\4\54\1\4\4"+
    "\37\1\232\4\146\1\157\4\21\1\304\4\274\1\57\4"+
    "\1\1\11\0\307\1\107\4\271\1\71\4\7\1\37\4"+
    "\1\1\12\0\146\1\36\4\2\1\5\0\13\1\60\4"+
    "\7\0\11\1\4\4\14\1\12\0\11\1\25\4\5\1"+
    "\23\4\260\1\100\4\200\1\113\4\4\1\1\0\1\4"+
    "\67\0\7\1\4\0\15\4\100\1\2\4\1\1\1\4"+
    "\1\0\13\1\2\0\16\1\370\4\10\1\326\4\52\1"+
    "\11\4\367\1\37\4\61\1\3\4\21\1\4\4\10\1"+
    "\u018c\4\4\1\153\4\5\1\15\4\3\1\11\4\7\1"+
    "\12\4\3\1\2\0\1\1\4\0\301\1\5\0\3\1"+
    "\26\0\2\1\7\0\36\1\4\0\224\1\3\0\273\1"+
    "\125\4\1\1\107\4\1\1\2\4\2\1\1\4\2\1"+
    "\2\4\2\1\4\4\1\1\14\4\1\1\1\4\1\1"+
    "\7\4\1\1\101\4\1\1\4\4\2\1\10\4\1\1"+
    "\7\4\1\1\34\4\1\1\4\4\1\1\5\4\1\1"+
    "\1\4\3\1\7\4\1\1\u0154\4\2\1\31\4\1\1"+
    "\31\4\1\1\37\4\1\1\31\4\1\1\37\4\1\1"+
    "\31\4\1\1\37\4\1\1\31\4\1\1\37\4\1\1"+
    "\31\4\1\1\10\4\2\1\151\0\4\1\62\0\10\1"+
    "\1\0\16\1\1\0\26\1\5\0\1\1\17\0\120\1"+
    "\7\0\1\1\21\0\2\1\7\0\1\1\2\0\1\1"+
    "\5\0\325\1\55\4\3\1\7\0\7\4\2\1\12\0"+
    "\4\1\1\4\u0171\1\54\4\16\0\5\1\306\4\13\1"+
    "\7\0\51\1\104\4\7\0\1\4\4\1\12\0\u0156\1"+
    "\1\4\117\1\4\4\1\1\33\4\1\1\2\4\1\1"+
    "\1\4\2\1\1\4\1\1\12\4\1\1\4\4\1\1"+
    "\1\4\1\1\1\4\6\1\1\4\4\1\1\4\1\1"+
    "\1\4\1\1\1\4\1\1\3\4\1\1\2\4\1\1"+
    "\1\4\2\1\1\4\1\1\1\4\1\1\1\4\1\1"+
    "\1\4\1\1\1\4\1\1\2\4\1\1\1\4\2\1"+
    "\4\4\1\1\7\4\1\1\4\4\1\1\4\4\1\1"+
    "\1\4\1\1\12\4\1\1\21\4\5\1\3\4\1\1"+
    "\5\4\1\1\21\4\u0134\1\12\0\6\1\336\4\42\1"+
    "\65\4\13\1\336\4\2\1\u0182\4\16\1\u0131\4\37\1"+
    "\36\4\342\1\113\4\266\1\1\0\36\1\140\0\200\1"+
    "\360\0\20\1";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[31232];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\3\1\1\2\1\3\2\1\1\4\1\5\1\6"+
    "\2\0\1\7\1\10";

  private static int [] zzUnpackAction() {
    int [] result = new int[15];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\13\0\26\0\41\0\13\0\13\0\54\0\67"+
    "\0\102\0\13\0\115\0\130\0\143\0\13\0\13";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[15];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\2\1\3\1\4\1\2\1\5\1\6\1\7\1\10"+
    "\2\2\15\0\1\11\1\0\1\11\2\12\4\11\2\0"+
    "\1\13\1\0\1\13\2\0\4\13\10\0\1\14\14\0"+
    "\1\15\1\11\1\0\1\11\1\0\1\11\2\0\4\11"+
    "\1\13\1\0\1\13\1\0\1\13\2\0\4\13\11\0"+
    "\1\16\10\0\1\17\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\2\11\3\1\1\11\1\1\2\0"+
    "\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[15];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  ItrulesLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return ItrulesTypes.TEXT;
            }
          // fall through
          case 9: break;
          case 2:
            { return ItrulesTypes.LEFT_SQUARE;
            }
          // fall through
          case 10: break;
          case 3:
            { return ItrulesTypes.RIGHT_SQUARE;
            }
          // fall through
          case 11: break;
          case 4:
            { return ItrulesTypes.MARK;
            }
          // fall through
          case 12: break;
          case 5:
            { return ItrulesTypes.SCAPED_CHAR;
            }
          // fall through
          case 13: break;
          case 6:
            { return ItrulesTypes.FORMATTER;
            }
          // fall through
          case 14: break;
          case 7:
            { return ItrulesTypes.DEFRULE;
            }
          // fall through
          case 15: break;
          case 8:
            { return ItrulesTypes.ENDRULE;
            }
          // fall through
          case 16: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
